# This file can be used for very simple installation that uses
# insecure urls (i.e. http, not httpS). This may not be be allowed in some environments
# and/or your browser may give a security warning
# Excellent choice for 1st time ISD Trial
#
# Instructions:
# a) Update the 3 URLs below
# b) Update the git repo details
# c) Follow the installation instructions to experience the next generation of Software Delivery
#
# NOTE: In the gitops-repo, locate the file "config", edit it and changed https to http for the "overrideurl" lines
#
global:
  ssl:
    enabled: false
  spinDeck:
    protocol: http
    host: spin.http-ryzon7.opsmx.co
  ## OES-UI url configuration
  oesUI:
    protocol: http
    host: oes.http-ryzon7.opsmx.co
  ## OES-Gate url configuration
  oesGate:
    protocol: http
    host: oes-gate.http-ryzon7.opsmx.co

spinnaker:
  gitopsHalyard:
    enabled: true
    repo:
      type: git # git, s3, stash(bitbucket server) use a different sample values file for s3/bitbuck-stash
      baseUrlHostName: github.com    # Specify it if git url is something other than github.com
      organization: ksrinimba
      # Specify project name only if repo is under a project
      projectName: ""
      repository: http-ryzon7 # repo name for GitOps Halyard (Sample Reference: https://github.com/OpsMx/sample-gitops-repo.git).
      dynamicAccRepository: http-ryzon7 # Please provide the repo name of the GitOps Dynamic Accounts Directory.Can be same as Hal repo. 
      username: ksrinimba  # Username to authenticate with git/stash repo
      token: <your get token> #  https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/creating-a-personal-access-token
    # Promote applications and pipelines from one environment to another or take backup

